name: Caleb1
favicon: null
layout_spectrum: 0.49696
typography_spectrum: 0.35226
title: Caleb Hudson
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#29393b'
    - '#e4ecf0'
    - '#d2ae9f'
    - '#815d41'
  brandStrength: 0.5
  lightness: 0.8496388089843094
  saturation: 0.4181972991209477
  rhythmicContrast: 0.08490370120853186
purpose: []
