name: Caleb1
favicon: null
layout_spectrum: 0.5086364522576332
typography_spectrum: 0.35190615081228316
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#bdc1bf'
    - '#84827e'
    - '#fdfdfd'
    - '#690000'
  brandStrength: 0.9184111359063536
  lightness: 0.8496388089843094
  saturation: 0.4181972991209477
  rhythmicContrast: 0.08490370120853186
purpose: []
